services:
  backend:
    image: hydrogendeuteride/lambert:latest
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - mongo
    command: ["node", "src/backend/index.js"]

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: change_password
      MONGO_INITDB_DATABASE: lambert